name: Publish Tags on PyPi when GitHub creates a release

# Controls when the workflow will run
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install upload dependencies
        run: |
          python -m pip install --upgrade --user pip setuptools wheel twine
      
      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish distribution to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*

      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*        
